dist: bionic
language: node_js
node_js: '16'

sudo: required
services:
  - docker

branches:
  only:
    - master  

before_script:
  - echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  - gcloud config set project $GCLOUD_PROJECT_ID
  - gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
  - gcloud container clusters get-credentials app-crud
  - gcloud auth configure-docker --quiet

jobs:
  include:
    - stage: Backend Deployment
      name: 'Run Backend Deployment'
      script:
        - cd App
        - npm test
        - docker build -t nestjs .
        - docker tag nestjs:latest ecstatic-galaxy-407119/api/nestjs:latest
        - docker push ecstatic-galaxy-407119/api/nestjs:latest

      deploy:
        provider: script
        script: bash ./deploy.sh
        on:
          branch: master  # Despliegue en la rama 'maste