apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: 860172129109.dkr.ecr.us-east-1.amazonaws.com/bff-repo
        ports:
        - containerPort: 4000
    resources:
      requests:
        cpu: "100m"  # 100 milicores (0.1 core)
        memory: "256Mi"  # 256 megabytes
      limits:
        cpu: "500m"  # 500 milicores (0.5 core)
        memory: "512Mi"  # 512 megabytes