version: '3.9'
services:
  app:
    image: nestjs
    hostname: app
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - server-network

  bff:
    hostname: bff
    image: nestjs-bff
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - server-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: apidatabase
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedromaironi
      MONGO_INITDB_ROOT_PASSWORD: 2171983
    networks:
      - server-network
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  elasticmq_cluster_1:
    image: softwaremill/elasticmq
    container_name: elasticmq_cluster_1
    networks:
      - server-network
    ports:
      - "9324:9324"
    restart: unless-stopped
  
  # elasticmq_cluster_2:
  #   image: softwaremill/elasticmq
  #   container_name: elasticmq_cluster_2
  #   networks:
  #     - server-network
  #   ports:
  #     - "9325:9325"
  #   restart: unless-stopped

  nexus:
    image: sonatype/nexus
    container_name: nexus
    ports:
      - "8081:8081"
    restart: unless-stopped

networks:
  server-network:

