apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cron
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: pedromaironi/backup:latest
            env:
            - name: MONGODB_URI
              value: "mongodb+srv://pedromaironi:2171983@appcrudclustermongo.tbzzw.mongodb.net/?retryWrites=true&w=majority&appName=AppCrudClusterMongo"
            - name: DATABASE_NAME
              value: "utesa"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: BUCKET_NAME
              value: "bucket-react-pedro"
            - name: BACKUP_FILE
              value: "user_backup.xlsx" 
            - name: BACKUP_PRODUCT_FILE
              value: "products_backup.xlsx" 
          restartPolicy: OnFailure